/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.mxmariner

import com.mxmariner.tiles.tiles
import kotlin.test.Test
import kotlin.test.assertNotNull

class TilesTest {
    @Test fun testVersion() {
        val classUnderTest = tiles()
        assertNotNull(classUnderTest.version, "there should be a version")
    }
}
